const champs = {
  all: [
    "Aatrox",
    "Ahri",
    "Akali",
    "Akshan",
    "Alistar",
    "Amumu",
    "Anivia",
    "Annie",
    "Aphelios",
    "Ashe",
    "AurelionSol",
    "Azir",
    "Bard",
    "Belveth",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Caitlyn",
    "Camille",
    "Cassiopeia",
    "Chogath",
    "Corki",
    "Darius",
    "Diana",
    "DrMundo",
    "Draven",
    "Ekko",
    "Elise",
    "Evelynn",
    "Ezreal",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Graves",
    "Gwen",
    "Hecarim",
    "Heimerdinger",
    "Illaoi",
    "Irelia",
    "Ivern",
    "Janna",
    "JarvanIV",
    "Jax",
    "Jayce",
    "Jhin",
    "Jinx",
    "Kaisa",
    "Kalista",
    "Karma",
    "Karthus",
    "Kassadin",
    "Katarina",
    "Kayle",
    "Kayn",
    "Kennen",
    "Khazix",
    "Kindred",
    "Kled",
    "KogMaw",
    "Leblanc",
    "LeeSin",
    "Leona",
    "Lillia",
    "Lissandra",
    "Lucian",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "MasterYi",
    "MissFortune",
    "Mordekaiser",
    "Morgana",
    "Nami",
    "Nasus",
    "Nautilus",
    "Neeko",
    "Nidalee",
    "Nilah",
    "Nocturne",
    "Nunu",
    "Olaf",
    "Orianna",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Quinn",
    "Rakan",
    "Rammus",
    "RekSai",
    "Rell",
    "Renata",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Ryze",
    "Samira",
    "Sejuani",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Sivir",
    "Skarner",
    "Sona",
    "Soraka",
    "Swain",
    "Sylas",
    "Syndra",
    "TahmKench",
    "Taliyah",
    "Talon",
    "Taric",
    "Teemo",
    "Thresh",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "TwistedFate",
    "Twitch",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Veigar",
    "Velkoz",
    "Vex",
    "Vi",
    "Viego",
    "Viktor",
    "Vladimir",
    "Volibear",
    "Warwick",
    "MonkeyKing",
    "Xayah",
    "Xerath",
    "XinZhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Yuumi",
    "Zac",
    "Zed",
    "Zeri",
    "Ziggs",
    "Zilean",
    "Zoe",
    "Zyra",
  ],
  top: [
    "Aatrox",
    "Akali",
    "Camille",
    "Chogath",
    "Darius",
    "DrMundo",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Illaoi",
    "Jax",
    "Jayce",
    "Kayle",
    "Kennen",
    "Kled",
    "Lillia",
    "Malphite",
    "Mordekaiser",
    "Nasus",
    "Olaf",
    "Ornn",
    "Pantheon",
    "Quinn",
    "Renekton",
    "Riven",
    "Rumble",
    "Sejuani",
    "Sett",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "TahmKench",
    "Teemo",
    "Tryndamere",
    "Udyr",
    "Urgot",
    "Vayne",
    "Volibear",
    "Yasuo",
    "Yone",
    "Yorick",
  ],
  jungle: [
    "Amumu",
    "Darius",
    "Ekko",
    "Evelynn",
    "Fiddlesticks",
    "Ivern",
    "JarvanIV",
    "Karthus",
    "Kayn",
    "Kindred",
    "LeeSin",
    "Lillia",
    "MasterYi",
    "Nidalee",
    "Nocturne",
    "Nunu",
    "Pantheon",
    "Poppy",
    "Rammus",
    "RekSai",
    "Rengar",
    "Sejuani",
    "Shaco",
    "Shyvana",
    "Skarner",
    "Taliyah",
    "Talon",
    "Trundle",
    "Udyr",
    "Vi",
    "Viego",
    "Volibear",
    "Warwick",
    "XinZhao",
    "Zac",
    "Zed",
  ],
  mid: [
    "Ahri",
    "Akali",
    "Akshan",
    "Anivia",
    "Annie",
    "AurelionSol",
    "Cassiopeia",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Cassiopeia",
    "Corki",
    "Diana",
    "Draven",
    "Ekko",
    "Elise",
    "Fiddlesticks",
    "Fizz",
    "Galio",
    "Gangplank",
    "Heimerdinger",
    "Irelia",
    "Jayce",
    "Karthus",
    "Kassadin",
    "Katarina",
    "Leblanc",
    "Lissandra",
    "Lucian",
    "Lux",
    "Malzahar",
    "Qiyana",
    "Neeko",
    "Orianna",
    "Pantheon",
    "Pyke",
    "Rumble",
    "Ryze",
    "Senna",
    "Seraphine",
    "Swain",
    "Sylas",
    "Syndra",
    "Taliyah",
    "Talon",
    "TwistedFate",
    "Veigar",
    "Velkoz",
    "Viego",
    "Viktor",
    "Vladimir",
    "Ziggs",
    "Zilean",
    "Zoe",
    "Zyra",
  ],
  adc: [
    "Caitlyn",
    "Aphelios",
    "Ashe",
    "Azir",
    "Draven",
    "Ezreal",
    "Graves",
    "Jhin",
    "Jinx",
    "Kaisa",
    "Kalista",
    "Kindred",
    "KogMaw",
    "Lucian",
    "Quinn",
    "MissFortune",
    "Vayne",
    "Veigar",
    "Xayah",
    "Xerath",
    "Yasuo",
    "Yone",
    "Ziggs",
    "Heimerdinger",
  ],
  support: [
    "Alistar",
    "Anivia",
    "Annie",
    "Braum",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Fiddlesticks",
    "Galio",
    "Gragas",
    "Ivern",
    "Janna",
    "Karma",
    "Leona",
    "Lissandra",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "Morgana",
    "Nami",
    "Nautilus",
    "Nunu",
    "Pantheon",
    "Pyke",
    "Rakan",
    "Rell",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Sion",
    "Sona",
    "Soraka",
    "Swain",
    "TahmKench",
    "Taric",
    "Thresh",
    "Velkoz",
    "Yuumi",
    "Zilean",
    "Zoe",
    "Zyra",
  ],
};

const mysticItem = [
  "Crown of the Shattered Queen",
  "Divine Sunderer",
  "Duskblade of Draktharr",
  "Eclipse",
  "Evenshroud",
  "Everfrost",
  "Frostfire Gauntlet",
  "Galeforce",
  "Goredrinker",
  "Hextech Rocketbelt",
  "Immortal Shieldbow",
  "Imperial Mandate",
  "Kraken Slayer",
  "Liandry's Anguish",
  "Locket of the Iron Solari",
  "Luden's Tempest",
  "Moonstone Renewer",
  "Night Harvester",
  "Prowler's Claw",
  "Riftmaker",
  "Shurelya's Battlesong",
  "Stridebreaker",
  "Sunfire Aegis",
  "Trinity Force",
  "Turbo Chemtank",
];

const normalItems = [
  "Abyssal Mask",
  "Anathema's Chains",
  "Archangel's Staff",
  "Ardent Censer",
  "Axiom Arc",
  "Banshee's Veil",
  "Black Cleaver",
  "Blade of The Ruined King",
  "Bloodthirster",
  "Chempunk Chainsword",
  "Chemtech Putrifier",
  "Cosmic Drive",
  "Dead Man's Plate",
  "Death's Dance",
  "Demonic Embrace",
  "Edge of Night",
  "Essence Reaver",
  "Force of Nature",
  "Frozen Heart",
  "Gargoyle Stoneplate",
  "Guardian Angel",
  "Guinsoo's Rageblade",
  "Horizon Focus",
  "Hullbreaker",
  "Infinity Edge",
  "Knight's Vow",
  "Lich Bane",
  "Lord Dominik's Regards",
  "Manamune",
  "Maw of Malmortius",
  "Mejai's Soulstealer",
  "Mercurial Scimitar",
  "Mikael's Blessing",
  "Morellonomicon",
  "Mortal Reminder",
  "Nashor's Tooth",
  "Navori Quickblades",
  "Phantom Dancer",
  "Rabadon's Deathcap",
  "Randuin's Omen",
  "Rapid Firecannon",
  "Ravenous Hydra",
  "Redemption",
  "Runaan's Hurricane",
  "Rylai's Crystal Scepter",
  "Serpent's Fang",
  "Serylda's Grudge",
  "Shadowflame",
  "Silvermere Dawn",
  "Spirit Visage",
  "Staff of Flowing Water",
  "Sterak's Gage",
  "Stormrazor",
  "The Collector",
  "Thornmail",
  "Titanic Hydra",
  "Umbral Glaive",
  "Vigilant Wardstone",
  "Void Staff",
  "Warmog's Armor",
  "Winter's Approach",
  "Wit's End",
  "Youmuu's Ghostblade",
  "Zeke's Convergence",
  "Zhonya's Hourglass",
];

const suppitems = [
  "Spellthief's Edge",
  "Steel Shoulderguards",
  "Relic Shield",
  "Spectral Sickle",
];

const boots = [
  "Berserker's Greaves",
  "Boots of Swiftness",
  "Ionian Boots of Lucidity",
  "Mercury's Treads",
  "Mobility Boots",
  "Plated Steelcaps",
  "Sorcerer's Shoes",
];
