const champs = {
  //TODO! do poprawy nazwy top jg mid adc support i pewnie itemy
  all: [
    "Aatrox",
    "Ahri",
    "Akali",
    "Akshan",
    "Alistar",
    "Amumu",
    "Anivia",
    "Annie",
    "Aphelios",
    "Ashe",
    "AurelionSol",
    "Azir",
    "Bard",
    "Belveth",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Caitlyn",
    "Camille",
    "Cassiopeia",
    "Chogath",
    "Corki",
    "Darius",
    "Diana",
    "DrMundo",
    "Draven",
    "Ekko",
    "Elise",
    "Evelynn",
    "Ezreal",
    "Fiddlesticks",
    "Fiora",
    "Fizz",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Graves",
    "Gwen",
    "Hecarim",
    "Heimerdinger",
    "Illaoi",
    "Irelia",
    "Ivern",
    "Janna",
    "JarvanIV",
    "Jax",
    "Jayce",
    "Jhin",
    "Jinx",
    "Kaisa",
    "Kalista",
    "Karma",
    "Karthus",
    "Kassadin",
    "Katarina",
    "Kayle",
    "Kayn",
    "Kennen",
    "Khazix",
    "Kindred",
    "Kled",
    "KogMaw",
    "Leblanc",
    "LeeSin",
    "Leona",
    "Lillia",
    "Lissandra",
    "Lucian",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "MasterYi",
    "MissFortune",
    "Mordekaiser",
    "Morgana",
    "Nami",
    "Nasus",
    "Nautilus",
    "Neeko",
    "Nidalee",
    "Nilah",
    "Nocturne",
    "Nunu",
    "Olaf",
    "Orianna",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Pyke",
    "Qiyana",
    "Quinn",
    "Rakan",
    "Rammus",
    "RekSai",
    "Rell",
    "Renata",
    "Renekton",
    "Rengar",
    "Riven",
    "Rumble",
    "Ryze",
    "Samira",
    "Sejuani",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Sivir",
    "Skarner",
    "Sona",
    "Soraka",
    "Swain",
    "Sylas",
    "Syndra",
    "Tahm Kench",
    "Taliyah",
    "Talon",
    "Taric",
    "Teemo",
    "Thresh",
    "Tristana",
    "Trundle",
    "Tryndamere",
    "TwistedFate",
    "Twitch",
    "Udyr",
    "Urgot",
    "Varus",
    "Vayne",
    "Veigar",
    "Velkoz",
    "Vex",
    "Vi",
    "Viego",
    "Viktor",
    "Vladimir",
    "Volibear",
    "Warwick",
    "Wukong",
    "Xayah",
    "Xerath",
    "XinZhao",
    "Yasuo",
    "Yone",
    "Yorick",
    "Yuumi",
    "Zac",
    "Zed",
    "Zeri",
    "Ziggs",
    "Zilean",
    "Zoe",
    "Zyra",
  ],
  top: [
    "Aatrox",
    "Akali",
    "Camille",
    "Cho'Gath",
    "Darius",
    "Dr.Mundo",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Illaoi",
    "Jax",
    "Jayce",
    "Kayle",
    "Kennen",
    "Kled",
    "Lillia",
    "Malphite",
    "Mordekaiser",
    "Nasus",
    "Olaf",
    "Ornn",
    "Pantheon",
    "Quinn",
    "Renekton",
    "Riven",
    "Rumble",
    "Sejuani",
    "Sett",
    "Shen",
    "Shyvana",
    "Singed",
    "Sion",
    "Tham Kench",
    "Teemo",
    "Tryndamere",
    "Udyr",
    "Urgot",
    "Vayne",
    "Volibear",
    "Yasuo",
    "Yone",
    "Yorick",
  ],
  jungle: [
    "Amumu",
    "Darius",
    "Ekko",
    "Evelynn",
    "Fiddlesticks",
    "Ivern",
    "Jarvan IV",
    "Karthus",
    "Kayn",
    "Kindred",
    "Lee Sin",
    "Lillia",
    "Master Yi",
    "Nidalee",
    "Nocturne",
    "Nunu and Willump",
    "Pantheon",
    "Poppy",
    "Rammus",
    "Rek'Sai",
    "Rengar",
    "Sejuani",
    "Shaco",
    "Shyvana",
    "Skarner",
    "Taliyah",
    "Talon",
    "Trundle",
    "Udyr",
    "Vi",
    "Viego",
    "Volibear",
    "Warwick",
    "Xin Zhao",
    "Zac",
    "Zed",
  ],
  mid: [
    "Ahri",
    "Akali",
    "Akshan",
    "Anivia",
    "Annie",
    "Aurelion Sol",
    "Cassiopeia",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Cassiopeia",
    "Corki",
    "Diana",
    "Draven",
    "Ekko",
    "Elise",
    "Fiddlesticks",
    "Fizz",
    "Galio",
    "Gangplank",
    "Heimerdinger",
    "Irelia",
    "Jayce",
    "Karthus",
    "Lee Sin",
    "Kassadin",
    "Katarina",
    "LeBlanc",
    "Lissandra",
    "Lucian",
    "Lux",
    "Malzahar",
    "Qiyana",
    "Neeko",
    "Orianna",
    "Pantheon",
    "Pyke",
    "Rumble",
    "Ryze",
    "Senna",
    "Seraphine",
    "Swain",
    "Sylas",
    "Syndra",
    "Taliyah",
    "Talon",
    "Twisted Fate",
    "Veigar",
    "Vel'Koz",
    "Viego",
    "Viktor",
    "Vladimir",
    "Ziggs",
    "Zilean",
    "Zoe",
    "Zyra",
  ],
  bottom: [
    "Caitlyn",
    "Aphelios",
    "Ashe",
    "Azir",
    "Bard",
    "Draven",
    "Ezreal",
    "Gnar",
    "Graves",
    "Jhin",
    "Jinx",
    "Kai'Sa",
    "Kalista",
    "Kindred",
    "Kog Maw",
    "Lucian",
    "Quinn",
    "Miss Fortune",
    "Vayne",
    "Veigar",
    "Xayah",
    "Xerath",
    "Yasuo",
    "Yone",
    "Ziggs",
    "Heimerdinger",
  ],
  support: [
    "Alistar",
    "Anivia",
    "Annie",
    "Braum",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Fiddlesticks",
    "Galio",
    "Gragas",
    "Ivern",
    "Janna",
    "Karma",
    "Leona",
    "Lissandra",
    "Lulu",
    "Lux",
    "Malphite",
    "Malzahar",
    "Maokai",
    "Morgana",
    "Nami",
    "Nautilus",
    "Nunu and Willump",
    "Pantheon",
    "Pyke",
    "Rakan",
    "Rell",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Sion",
    "Sona",
    "Soraka",
    "Swain",
    "Tahm Kench",
    "Taric",
    "Thresh",
    "Vel'Koz",
    "Yuumi",
    "Zilean",
    "Zoe",
    "Zyra",
  ],
};

const mysticItem = [
  "Divine Sunderer",
  "Duskblade of Draktharr",
  "Eclipse",
  "Everfrost",
  "Frostfire Gauntlet",
  "Galeforce",
  "Goredrinker",
  "Hextech Rocketbelt",
  "Immortal Shieldbow",
  "Imperial Mandate",
  "Kraken Slayer",
  "Liandry's Anguish",
  "Locket of the Iron Solari",
  "Luden's Tempest",
  "Moonstone Renewer",
  "Night Harvester",
  "Prowler's Claw",
  "Riftmaker",
  "Shurelya's Battlesong",
  "Stridebreaker",
  "Sunfire Aegis",
  "Trinity Force",
  "Turbo Chemtank",
];

const items = [
  "The Collector",
  "Navori Quickblades",
  "Force of Nature",
  "Serpent’s Fang",
  "Horizon Focus",
  "Cosmic Drive",
  "Demonic Embrace",
  "Abyssal Mask",
  "Archangel's Staff",
  "Ardent Censer",
  "Banshee's Veil",
  "Black Cleaver",
  "BOTRK",
  "Bloodthirster",
  "Chempunk Chainsword",
  "Chemtech Putrifier",
  "Dead Man's Plate",
  "Death's Dance",
  "Edge of Night",
  "Essence Reaver",
  "Frozen Heart",
  "Gargoyle Stoneplate",
  "Guradian Angel",
  "Guinsoo's Rageblade",
  "Infinity Edge",
  "Knight's Vow",
  "Lich Bane",
  "Lord Dominik's Regards",
  "Manamune",
  "Maw of Malmortius",
  "Mejai's Soulstraler",
  "Mercurial Scimitar",
  "Mikael's Blessing",
  "Morellonomicon",
  "Mortal Reminder",
  "Muramana",
  "Nashor's Tooth",
  "Phantom Dancer",
  "Rabadon's Deathcap",
  "Randuin's Omen",
  "Rapid Firecannon",
  "Ravenous Hydra",
  "Redemption",
  "Runaan's Hurricane",
  "Rylai's Crystal Scepter",
  "Sanguine Blade",
  "Serylda's Grudge",
  "Silvermere Dawn",
  "Spirit Visage",
  "Sterak's Gage",
  "Stormrazor",
  "Thornmail",
  "Titanic Hydra",
  "Umbral Glaive",
  "Void Staff",
  "Warmog's Armor",
  "Wit's End",
  "Youmuu's Ghostblade",
  "Zeke's Convergence",
  "Zhonya's Hourglass",
];

const suppitems = [
  "Spellthief’s Edge",
  "Steel Shoulderguards",
  "Relic Shield",
  "Spectral Sickle",
];

const boots = [
  "Berserker's Greaves",
  "Boots of Swiftness",
  "Ionian Boots of Lucidity",
  "Mercury's Treads",
  "Mobility Boots",
  "Plated Steelcaps",
  "Sorcerer's Shoes",
];
